### ISSUE TITLE
Apptforpatient/apptfordoctor/edit error message is incorrect

### ISSUE THREAD

**Issue by ararchch** [AY2324S2-CS2103T-T15-1/tp#116]
Currently apptforpatient/apptfordoctor only query by NRIC but the error message still says 'name'.
Edit error message has tags.

**Comment by Kappaccinoh** [comment]
<img width="590" alt="image" src="https://github.com/AY2324S2-CS2103T-T15-1/tp/assets/83304120/55db7148-b345-47d1-8c81-ab1801d26443">

Example also needs to change

apptfordoctor alice bob T1234567A S7654321A
^Remove alice and bob

**Comment by Kappaccinoh** [comment]
<img width="515" alt="image" src="https://github.com/AY2324S2-CS2103T-T15-1/tp/assets/83304120/aa044d00-3918-4569-b513-706883ca1462">

error message should show patient
